name: Deploy to EKS

on:
  push:
    branches:
      - main

ignore:
  - paths:
      - 'README.md'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region ap-south-1 | \
        docker login --username AWS --password-stdin 178502900821.dkr.ecr.ap-south-1.amazonaws.com

    - name: Build and tag Docker image
      run: |
        docker build -t smartpay .
        docker tag smartpay:latest 178502900821.dkr.ecr.ap-south-1.amazonaws.com/smartpay-service:latest

    - name: Push image to ECR
      run: | 
        docker push 178502900821.dkr.ecr.ap-south-1.amazonaws.com/smartpay-service:latest


    - name: Update deployment in EKS
      run: |
        aws eks update-kubeconfig --region ap-south-1 --name smartpay-cluster
        kubectl rollout restart deployment smartpay


